/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    organizations: Organization;
    opportunities: Opportunity;
    events: Event;
    'event-assets': EventAsset;
    'organization-assets': OrganizationAsset;
    'organization-invites': OrganizationInvite;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    users: {
      organizations: 'organizations';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    organizations: OrganizationsSelect<false> | OrganizationsSelect<true>;
    opportunities: OpportunitiesSelect<false> | OpportunitiesSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'event-assets': EventAssetsSelect<false> | EventAssetsSelect<true>;
    'organization-assets': OrganizationAssetsSelect<false> | OrganizationAssetsSelect<true>;
    'organization-invites': OrganizationInvitesSelect<false> | OrganizationInvitesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'event-settings': EventSetting;
    'site-settings': SiteSetting;
    'payload-jobs-stats': PayloadJobsStat;
  };
  globalsSelect: {
    'event-settings': EventSettingsSelect<false> | EventSettingsSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'payload-jobs-stats': PayloadJobsStatsSelect<false> | PayloadJobsStatsSelect<true>;
  };
  locale: null;
  user: User;
  jobs: {
    tasks: {
      mobilizeSync: TaskMobilizeSync;
      googleCalendarSync: TaskGoogleCalendarSync;
      scanPoster: TaskScanPoster;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: {
      syncEvents: WorkflowSyncEvents;
      manualSyncEvents: WorkflowManualSyncEvents;
    };
  };
}
export interface UserAuthOperations {
  forgotPassword:
    | {
        email: string;
      }
    | {
        username: string;
      };
  login:
    | {
        email: string;
        password: string;
      }
    | {
        password: string;
        username: string;
      };
  registerFirstUser: {
    password: string;
    username: string;
    email?: string;
  };
  unlock:
    | {
        email: string;
      }
    | {
        username: string;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  roles: ('admin' | 'organizer')[];
  inviteCode?: string | null;
  organizationName?: string | null;
  organizationDescription?: string | null;
  organizationContactMethods?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  organizationContactEmail?: string | null;
  organizationContactPhone?: string | null;
  organizationContactPage?: string | null;
  invite?: (string | null) | OrganizationInvite;
  organizations?: {
    docs?: (string | Organization)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  email?: string | null;
  username: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organization-invites".
 */
export interface OrganizationInvite {
  id: string;
  /**
   * The secure code used for the invite link.
   */
  code: string;
  /**
   * The total number of organizations that the recipient can create after the invite is accepted. Max 10.
   */
  organizationTokens: number;
  expiresIn: '1day' | '3days' | '1week' | '2weeks' | '1month' | 'date';
  expirationDate?: string | null;
  status: 'pending' | 'accepted' | 'expired';
  usedBy?: (string | null) | User;
  createdBy: string | User;
  /**
   * (Optional) Internal notes for this invitation. These are only visible to site administrators.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations".
 */
export interface Organization {
  id: string;
  name: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * If your organization has events on Mobilize, please provide the slug or URL for your organization on Mobilize. This prevents duplicate events from being created from Mobilize if you use Google Calendar integration and ensures accurate event listings.
   */
  mobilizeSlug?: string | null;
  organizers: (string | User)[];
  logo?: (string | null) | OrganizationAsset;
  publicContactMethods?: {
    showEmail?: boolean | null;
    contactEmail?: string | null;
    contactEmailLabel?: string | null;
    showPhone?: boolean | null;
    contactPhone?: string | null;
    contactPhoneLabel?: string | null;
    showWebsite?: boolean | null;
    contactWebsite?: string | null;
    contactWebsiteLabel?: string | null;
  };
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  opportunities?: (string | Opportunity)[] | null;
  /**
   * Allow this organization to sync events from a Google Calendar.
   */
  enableGoogleCalendarSync?: boolean | null;
  googleCalendarId?: string | null;
  /**
   * A default image used for calendar events from this organization when no event-specific image is available.
   */
  defaultEventImage?: (string | null) | OrganizationAsset;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organization-assets".
 */
export interface OrganizationAsset {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "opportunities".
 */
export interface Opportunity {
  id: string;
  name: string;
  /**
   * A brief description of the activity that is organization-agnostic, i.e. "Sharing resources and providing direct support to meet community needs".
   */
  description?: string | null;
  status?: ('pending' | 'verified') | null;
  requestedBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: string;
  /**
   * The name of this event.
   */
  title: string;
  /**
   * A brief description of this event.
   */
  description: string;
  url: string;
  date: string;
  endDate?: string | null;
  location?: {
    country?: 'US' | null;
    state?:
      | (
          | 'AL'
          | 'AK'
          | 'AZ'
          | 'AR'
          | 'CA'
          | 'CO'
          | 'CT'
          | 'DE'
          | 'DC'
          | 'FL'
          | 'GA'
          | 'HI'
          | 'ID'
          | 'IL'
          | 'IN'
          | 'IA'
          | 'KS'
          | 'KY'
          | 'LA'
          | 'ME'
          | 'MD'
          | 'MA'
          | 'MI'
          | 'MN'
          | 'MS'
          | 'MO'
          | 'MT'
          | 'NE'
          | 'NV'
          | 'NH'
          | 'NJ'
          | 'NM'
          | 'NY'
          | 'NC'
          | 'ND'
          | 'OH'
          | 'OK'
          | 'OR'
          | 'PA'
          | 'RI'
          | 'SC'
          | 'SD'
          | 'TN'
          | 'TX'
          | 'UT'
          | 'VT'
          | 'VA'
          | 'WA'
          | 'WV'
          | 'WI'
          | 'WY'
        )
      | null;
    city?: string | null;
    address?: string | null;
    postalCode?: string | null;
    venue?: string | null;
  };
  eventType?: string | null;
  source?: ('local' | 'googleCalendar' | 'mobilize') | null;
  local?: {
    images?: (string | EventAsset)[] | null;
    organization?: (string | null) | Organization;
    /**
     * The user who created this event. This is only visible to site administrators.
     */
    createdBy: string | User;
  };
  googleCalendar?: {
    eventId: string;
    calendarId: string;
    organization?: (string | null) | Organization;
  };
  mobilize?: {
    eventId: number;
    image?: string | null;
    organization: {
      orgId: number;
      name: string;
      slug: string;
      url: string;
    };
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-assets".
 */
export interface EventAsset {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'mobilizeSync' | 'googleCalendarSync' | 'scanPoster';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  workflowSlug?: ('syncEvents' | 'manualSyncEvents') | null;
  taskSlug?: ('inline' | 'mobilizeSync' | 'googleCalendarSync' | 'scanPoster') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  /**
   * Used for concurrency control. Jobs with the same key are subject to exclusive/supersedes rules.
   */
  concurrencyKey?: string | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'organizations';
        value: string | Organization;
      } | null)
    | ({
        relationTo: 'opportunities';
        value: string | Opportunity;
      } | null)
    | ({
        relationTo: 'events';
        value: string | Event;
      } | null)
    | ({
        relationTo: 'event-assets';
        value: string | EventAsset;
      } | null)
    | ({
        relationTo: 'organization-assets';
        value: string | OrganizationAsset;
      } | null)
    | ({
        relationTo: 'organization-invites';
        value: string | OrganizationInvite;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  inviteCode?: T;
  organizationName?: T;
  organizationDescription?: T;
  organizationContactMethods?: T;
  organizationContactEmail?: T;
  organizationContactPhone?: T;
  organizationContactPage?: T;
  invite?: T;
  organizations?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  username?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations_select".
 */
export interface OrganizationsSelect<T extends boolean = true> {
  name?: T;
  generateSlug?: T;
  slug?: T;
  mobilizeSlug?: T;
  organizers?: T;
  logo?: T;
  publicContactMethods?:
    | T
    | {
        showEmail?: T;
        contactEmail?: T;
        contactEmailLabel?: T;
        showPhone?: T;
        contactPhone?: T;
        contactPhoneLabel?: T;
        showWebsite?: T;
        contactWebsite?: T;
        contactWebsiteLabel?: T;
      };
  description?: T;
  opportunities?: T;
  enableGoogleCalendarSync?: T;
  googleCalendarId?: T;
  defaultEventImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "opportunities_select".
 */
export interface OpportunitiesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  status?: T;
  requestedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  url?: T;
  date?: T;
  endDate?: T;
  location?:
    | T
    | {
        country?: T;
        state?: T;
        city?: T;
        address?: T;
        postalCode?: T;
        venue?: T;
      };
  eventType?: T;
  source?: T;
  local?:
    | T
    | {
        images?: T;
        organization?: T;
        createdBy?: T;
      };
  googleCalendar?:
    | T
    | {
        eventId?: T;
        calendarId?: T;
        organization?: T;
      };
  mobilize?:
    | T
    | {
        eventId?: T;
        image?: T;
        organization?:
          | T
          | {
              orgId?: T;
              name?: T;
              slug?: T;
              url?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-assets_select".
 */
export interface EventAssetsSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organization-assets_select".
 */
export interface OrganizationAssetsSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organization-invites_select".
 */
export interface OrganizationInvitesSelect<T extends boolean = true> {
  code?: T;
  organizationTokens?: T;
  expiresIn?: T;
  expirationDate?: T;
  status?: T;
  usedBy?: T;
  createdBy?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  workflowSlug?: T;
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  concurrencyKey?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-settings".
 */
export interface EventSetting {
  id: string;
  events: {
    /**
     * Configure site settings for events uploaded to the site through the dashboard.
     */
    localEvents?: {
      enableLocalEvents?: boolean | null;
    };
    /**
     * Configure site settings for Google Calendar events. Syncs with event calendar every 4 hours by default.
     */
    googleCalendar?: {
      enableGoogleCalendar?: boolean | null;
      /**
       * Get an API key from https://developers.google.com/calendar/quickstart/js
       */
      googleCalendarApiKey?: string | null;
      /**
       * Allow organizers to add Google Calendar synchronization for their organization's events. This will allow them to add events to the organization's calendar and automatically update the events on the site.
       */
      enableOrganizationCalendars?: boolean | null;
      /**
       * Global calendars included in the event synchronization.
       */
      googleCalendars?:
        | {
            name?: string | null;
            calendarId: string;
            id?: string | null;
          }[]
        | null;
    };
    /**
     * Configure site settings for Mobilize events. Syncs with event calendar every 4 hours by default.
     */
    mobilize: {
      enableMobilize?: boolean | null;
      /**
       * Optional, currently unused.
       */
      mobilizeApiKey?: string | null;
      enableStateFilter: boolean;
      /**
       * Filter events by state. Required by default when enabling mobilize integration to limit total number of events fetched.
       */
      stateFilter?: {
        state:
          | 'AL'
          | 'AK'
          | 'AZ'
          | 'AR'
          | 'CA'
          | 'CO'
          | 'CT'
          | 'DE'
          | 'DC'
          | 'FL'
          | 'GA'
          | 'HI'
          | 'ID'
          | 'IL'
          | 'IN'
          | 'IA'
          | 'KS'
          | 'KY'
          | 'LA'
          | 'ME'
          | 'MD'
          | 'MA'
          | 'MI'
          | 'MN'
          | 'MS'
          | 'MO'
          | 'MT'
          | 'NE'
          | 'NV'
          | 'NH'
          | 'NJ'
          | 'NM'
          | 'NY'
          | 'NC'
          | 'ND'
          | 'OH'
          | 'OK'
          | 'OR'
          | 'PA'
          | 'RI'
          | 'SC'
          | 'SD'
          | 'TN'
          | 'TX'
          | 'UT'
          | 'VT'
          | 'VA'
          | 'WA'
          | 'WV'
          | 'WI'
          | 'WY';
      };
      enableOrganizationFilter?: boolean | null;
      organizationFilter?: {
        type: 'allowlist' | 'blocklist';
        list: string[];
      };
    };
  };
  calendar: {
    /**
     * The range of how many past and future months are displayed in the calendar view. Max 12 months. For example, a months range of 6 months will display the current month, the past 6 months, and the next 6 months.
     */
    monthsRange: number;
    /**
     * Synchronize with all event sources and update calendar events.
     */
    syncInterval: number;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  'site-disclaimer'?: {
    enableSiteDisclaimer?: boolean | null;
    title?: string | null;
    message?: string | null;
    buttonText?: string | null;
  };
  location?: {
    defaultCountry?: 'US' | null;
    defaultState?:
      | (
          | 'AL'
          | 'AK'
          | 'AZ'
          | 'AR'
          | 'CA'
          | 'CO'
          | 'CT'
          | 'DE'
          | 'DC'
          | 'FL'
          | 'GA'
          | 'HI'
          | 'ID'
          | 'IL'
          | 'IN'
          | 'IA'
          | 'KS'
          | 'KY'
          | 'LA'
          | 'ME'
          | 'MD'
          | 'MA'
          | 'MI'
          | 'MN'
          | 'MS'
          | 'MO'
          | 'MT'
          | 'NE'
          | 'NV'
          | 'NH'
          | 'NJ'
          | 'NM'
          | 'NY'
          | 'NC'
          | 'ND'
          | 'OH'
          | 'OK'
          | 'OR'
          | 'PA'
          | 'RI'
          | 'SC'
          | 'SD'
          | 'TN'
          | 'TX'
          | 'UT'
          | 'VT'
          | 'VA'
          | 'WA'
          | 'WV'
          | 'WI'
          | 'WY'
        )
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats".
 */
export interface PayloadJobsStat {
  id: string;
  stats?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-settings_select".
 */
export interface EventSettingsSelect<T extends boolean = true> {
  events?:
    | T
    | {
        localEvents?:
          | T
          | {
              enableLocalEvents?: T;
            };
        googleCalendar?:
          | T
          | {
              enableGoogleCalendar?: T;
              googleCalendarApiKey?: T;
              enableOrganizationCalendars?: T;
              googleCalendars?:
                | T
                | {
                    name?: T;
                    calendarId?: T;
                    id?: T;
                  };
            };
        mobilize?:
          | T
          | {
              enableMobilize?: T;
              mobilizeApiKey?: T;
              enableStateFilter?: T;
              stateFilter?:
                | T
                | {
                    state?: T;
                  };
              enableOrganizationFilter?: T;
              organizationFilter?:
                | T
                | {
                    type?: T;
                    list?: T;
                  };
            };
      };
  calendar?:
    | T
    | {
        monthsRange?: T;
        syncInterval?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  'site-disclaimer'?:
    | T
    | {
        enableSiteDisclaimer?: T;
        title?: T;
        message?: T;
        buttonText?: T;
      };
  location?:
    | T
    | {
        defaultCountry?: T;
        defaultState?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats_select".
 */
export interface PayloadJobsStatsSelect<T extends boolean = true> {
  stats?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskMobilizeSync".
 */
export interface TaskMobilizeSync {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskGoogleCalendarSync".
 */
export interface TaskGoogleCalendarSync {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskScanPoster".
 */
export interface TaskScanPoster {
  input: {
    imageIds: {
      id: string;
    }[];
    userId: string;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WorkflowSyncEvents".
 */
export interface WorkflowSyncEvents {
  input?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WorkflowManualSyncEvents".
 */
export interface WorkflowManualSyncEvents {
  input: {
    userId: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}