const initialOrganizations = [
  { value: "19", label: "Armed Queers Salt Lake City" },
  { value: "2", label: "Bakers for Palestine" },
  { value: "20", label: "BTMC" },
  { value: "13", label: "Cache Valley Mutual Aid" },
  { value: "22", label: "Camping in Color SLC" },
  { value: "16", label: "Comunidades Unidas" },
  { value: "3", label: "DSA" },
  { value: "24", label: "Fish For Garbage" },
  { value: "11", label: "Green Wave Utah" },
  { value: "25", label: "ibikeutah" },
  { value: "1", label: "Indivisible" },
  { value: "8", label: "Ken Sanders Rare Books" },
  { value: "10", label: "MyUEA" },
  { value: "26", label: "Project Rainbow" },
  { value: "27", label: "Salt Lake Area Queer Climbers" },
  { value: "14", label: "Salt Lake Harm Reduction Project" },
  { value: "15", label: "Sierra Club Utah" },
  { value: "4", label: "SLC Mutual Aid" },
  { value: "12", label: "SLCounty Community Exchange" },
  { value: "28", label: "SLC Queer Latin Dance" },
  { value: "9", label: "uhwunited" },
  { value: "30", label: "Under the Umbrella Bookstore" },
  { value: "7", label: "United Mountain Workers" },
  { value: "18", label: "Urban Indian Center of Salt Lake" },
  { value: "17", label: "Utah State Progressive Caucus" },
  { value: "31", label: "Wasatch Community Gardens" },
  { value: "32", label: "Wasatch Trails Collective" },
  { value: "__add_new__", label: "+ Add New Organization" },
];
